output "cloudwatch_log_group_name" {
  description = "Name of cloudwatch log group created"
  value       = "${module.eks.cloudwatch_log_group_name}"
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = "${module.eks.cluster_endpoint}"
}

output "cluster_id" {
  description = "The name/id of the EKS cluster."
  value       = "${module.eks.cluster_id}"
}

output "cluster_version" {
  description = "The Kubernetes server version for the EKS cluster."
  value       = "${module.eks.cluster_version}"
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = "${module.eks.cluster_security_group_id}"
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = "${module.eks.kubeconfig}"
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = "${module.eks.config_map_aws_auth}"
}

output "workers_asg_arns" {
  description = "IDs of the autoscaling groups containing workers."
  value       = "${module.eks.workers_asg_arns}"
}

output "workers_asg_names" {
  description = "Names of the autoscaling groups containing workers."
  value       = "${module.eks.workers_asg_names}"
}

output "workers_launch_template_ids" {
  description = "IDs of the worker launch templates."
  value       = "${module.eks.workers_launch_template_ids}"
}

output "workers_user_data" {
  description = "User data of worker groups"
  value       = "${module.eks.workers_user_data}"
}

